// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MyraCtxStatus } from "./MyraCtxStatus";

/**
 * A version-aware documentation lookup served by MyraCtx.
 */
export type MyraCtxItem = { id: string, library: string, query: string, status: MyraCtxStatus, };
