// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebFetchStatus } from "./WebFetchStatus";

/**
 * A page read through the gateway's fetcher.
 *
 * Separate from [`crate::web_search::WebSearchItem`] because a fetch is a
 * different act with a different useful detail: one URL and the title behind
 * it, rather than a query and a result set.
 */
export type WebFetchItem = { id: string, url: string,
/**
 * The page's own title, known only once the fetch returns.
 */
title: string | null, status: WebFetchStatus, };
